version: "3.3"

services:
  ### PHP-FPM Container #######################################

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'

  swoole:
    container_name: swoole
    tty: true
    restart: unless-stopped
    working_dir: /app
    build:
      context: ./swoole
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    volumes:
      - ./swoole:/app/
    networks:
      - app-network

  php1:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
      - ./php/additional.ini:/usr/local/etc/php/conf.d/additional.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - app-network

  ### Nginx Server Container ##################################

  nginx1:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - php
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      TZ: Asia/Shanghai
    volumes:
      - ./:/var/www/php
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
